#release configuration
#Sat May 22 21:39:01 BST 2021
projectVersionPolicyId=default
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
project.scm.com.robgro\:rg-pet-clinic.developerConnection=scm\:git@github.com/rob-gro/rg-pet-clinic.git
project.dev.com.robgro\:rg-pet-clinic=0.0.3-SNAPSHOT
project.rel.com.robgro\:pet-clinic-web=0.0.2
project.dev.com.robgro\:pet-clinic-web=0.0.3-SNAPSHOT
project.rel.com.robgro\:pet-clinic-data=0.0.2
completedPhase=run-preparation-goals
project.dev.com.robgro\:pet-clinic-data=0.0.3-SNAPSHOT
scm.url=scm\:git\:git@github.com/rob-gro/rg-pet-clinic
project.rel.com.robgro\:rg-pet-clinic=0.0.2
project.scm.com.robgro\:pet-clinic-web.empty=true
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.com.robgro\:pet-clinic-data.empty=true
scm.tag=0.0.2
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.scm.com.robgro\:rg-pet-clinic.tag=HEAD
